const userRouter = require('./routers/userRouter')
const loginRouter = require('./routers/loginRouter')
const specializationRouter = require('./routers/specializationRouter')
const doctorRouter = require('./routers/doctorRouter')
const patientRouter = require('./routers/patientRouter')
const appointmentRouter = require('./routers/appointmentRouter')
const prescriptionRouter = require('./routers/prescriptionRouter')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const securityMiddleware = require('./middleware/securityMiddleware')
const authMiddleware = require('./middleware/authMiddleware')
const express = require('express')
const app = express()
app.use(bodyParser.json())
app.use(cookieParser())
app.use(authMiddleware)
app.use(securityMiddleware)
app.use('/users', userRouter)
app.use('/auth', loginRouter)
app.use('/specializations', specializationRouter)
app.use('/doctors', doctorRouter)
app.use('/patients', patientRouter)
app.use('/appointments', appointmentRouter)
app.use('/prescriptions', prescriptionRouter)
module.exports = app
