name: CI
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
  compose_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compose
        uses: adambirds/docker-compose-action@v1.3.0
        with:
            compose-file: "./docker-compose.yml"
            down-flags: "--wait"
            services: |
                    hospital-app
                    hospital-auth
                    hospital-database
                    hospital-database-test
            test-container: hospital-app
            test-command: npm test
