name: CI
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
jobs:
  compose_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linting
        run: npm run lint
      - name: "Set up environment"
        run: docker compose -f docker-compose-test.yml up -d --wait 
      - name: "Run tests"
        run: docker exec hospital-hospital-app-1 npm test
